config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create_with_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  resources :relationships
  resources :message_recipients
  resources :messages
	root 'sessions#login'
	resources :sessions, only: [:create]
	get 'login' => 'sessions#login'
	delete 'logout' => 'sessions#destroy'
  	resources :users
  	get 'messages_page' => 'users#show_message'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :message_recipients
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
		@outgoing_message = OutgoingMessage.new
		@relationships = Relationship.where(friend_id: current_user.id, relationship_status: 1)
	end

	def create

		if (!params[:recipients].nil?) && params[:recipients].any? && params[:subject].present? && params[:content].present?
			@recipients = params[:recipients]

			@recipients.each do |recipient|
				@user = User.find_by(email: recipient)
				if @user
					Message.create(message_type: 'TEXT', user_id: current_user.id, recipient_id: @user.id, title: params[:subject], content: params[:content], status: 1)
					
				end				
			end

			redirect_to new_message_path, flash: {success: 'Your message have successfully sent to your friend(s)'}
		else
			redirect_to new_message_path, notice: 'All fields are required!'
		end
	end

	def show
		if params[:id]
			puts "current_user.id: "
			puts params[:id].to_s
			# @message_ids = session[:message_recipients].select{|x| x["sender_id"].to_s == params[:id].to_s}

			# MessageRecipient.where(id: @message_ids.collect{|mss| mss["id"]}).update_all(status: 2)

			# @messages_list = Message.where(id: @message_ids.collect{|mss| mss["message_id"]})
			if current_user.id.to_i == params[:id].to_i
				@messages_list = Message.where(user_id: params[:id]).order('created_at DESC')
			else
				@messages_list = Message.where(user_id: params[:id], recipient_id: current_user.id).order('created_at DESC')
			end
			
		end
	end

	def update
		if params[:id]

			Message.where(id: params[:id], status: 1).update(status: 2) #already read the message
		end
	end

	# private
	# def outgoing_message_params
	# 	params.require(:outgoing_message).permit(:subject, :content, 'recipients[]')
	# end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/new.html.erb
<%= form_tag(messages_path, method: 'post') do %>
    
    <div class="row">
      <div class="col-md-7">
        <div class="form-group row">
          <label class="col-md-2 col-sm-2 col-xs-2 col-form-label">To:</label>
          <div class="col-md-10">
            <div class="form-control" id="recipients-list">
              
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-md-2 col-sm-2 col-xs-2 col-form-label">Subject:</label>
          <div class="col-md-10">
            <%= text_field_tag :subject, nil, class:'form-control', placeholder:'Message Subject', type:'text' %>       
          </div>
        </div>
        <div class="form-group row">
          <label class="col-md-2 col-sm-2 col-xs-2 col-form-label">Content:</label>
          <div class="col-md-10">
            <%= text_area_tag :content, nil, class:'form-control', placeholder:'What do you wanna tell your friends?', type:'text' %> 
          </div>      
        </div>
        <div class="row">
        <div class="col-md-2">
          
        </div>
          <div class="col-md-3 col-md-offset-2">
            <%= submit_tag("Send message", :class=>"btn btn-primary") %>  
          </div>          
        </div>
        
      </div>
      <div class="col-md-5">
        <div class="form-control">
          <%= render '/relationships/friend_list' %>
        </div>
      </div>
      
    </div>
    

<% end %>

app/views/messages/show.js.erb
$(".messages-content").html("<%= escape_javascript(render '/users/show_message_content_form') %>")