config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create_with_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  resources :relationships
  resources :message_recipients
  resources :messages
	root 'sessions#login'
	resources :sessions, only: [:create]
	get 'login' => 'sessions#login'
	delete 'logout' => 'sessions#destroy'
  	resources :users
  	get 'messages_page' => 'users#show_message'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	# status: 0. request, 1 friends, 2. be requested
  belongs_to :user
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def new
		@users = User.joins('left join relationships on users.id = relationships.user_id and relationships.friend_id = ' + current_user.id.to_s).where('users.id != ?', current_user.id).select('users.id as id, users.name as name, users.email as email, case when relationships.relationship_status is null then -1 else relationships.relationship_status end as status')
		puts @users.class
		puts @users.inspect
	end

	def create
		
		if params[:friend_id]
			@relationship_count = Relationship.where(user_id: current_user.id, friend_id: params[:friend_id]).count
			if @relationship_count == 0
				Relationship.create(user_id: current_user.id, friend_id: params[:friend_id], relationship_status: 0, action: 1)
				Relationship.create(user_id: params[:friend_id], friend_id: current_user.id, relationship_status: 2, action: 1)
			end
		end

		@users = User.joins('left join relationships on users.id = relationships.user_id and relationships.friend_id = ' + current_user.id.to_s).where('users.id != ?', current_user.id).select('users.id as id, users.name as name, users.email as email, case when relationships.relationship_status is null then -1 else relationships.relationship_status end as status')
	end

	def update
		if params[:id]
			Relationship.where(user_id: current_user.id, friend_id: params[:id]).update(relationship_status: 1)
			Relationship.where(user_id: params[:id], friend_id: current_user.id).update(relationship_status: 1)
			@users = User.joins('left join relationships on users.id = relationships.user_id and relationships.friend_id = ' + current_user.id.to_s).where('users.id != ?', current_user.id).select('users.id as id, users.name as name, users.email as email, case when relationships.relationship_status is null then -1 else relationships.relationship_status end as status')
		end
	end

	def destroy
		if params[:id]
			Relationship.destroy_all(user_id: current_user.id, friend_id: params[:id])
			Relationship.destroy_all(user_id: params[:id], friend_id: current_user.id)
			@users = User.joins('left join relationships on users.id = relationships.user_id and relationships.friend_id = ' + current_user.id.to_s).where('users.id != ?', current_user.id).select('users.id as id, users.name as name, users.email as email, case when relationships.relationship_status is null then -1 else relationships.relationship_status end as status')
		end
	end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_friend_list.html.erb
<% if @relationships.nil? || @relationships.count < 0 %>
	<p class="text_muted">You have no friend</p>
<% else %>
	<% @relationships.each do |relationship| %>
		<li class="list-group-item"> <%= relationship.user.name %> 
			<a href="#" data-remote="true" onclick="windChat_add_recipient('<%= relationship.user.email %>')" class="pull-xs-right" >Add as Recipient</a>
		</li>
	<% end %>
<% end %>

app/views/relationships/_user_list.html.erb
<% if @users.nil? || @users.any? == false %>
	<p class="text_muted">Poor you! You're the only one in this network. Are you scared? Go tell your friends to join you! </p>
<% else %>
	<% @users.each do |user| %>
		<li class="list-group-item"> <%= user.name %> 
			<% if user.status < 0 %>
				<%= form_tag(relationships_path, remote: true, method: 'post', class: 'add-friend-form form-inline pull-xs-right') do %>
					<%= hidden_field_tag :friend_id, user.id %>
					<%= submit_tag "Add Friend", class: "btn-link pull-xs-right float-xs-right link-friend-list" %>
				<% end %>
			<% elsif user.status == 0 %>
				<%= link_to relationship_path(user.id), method: 'put', remote: true, :class => 'pull-xs-right link-friend-list' do %>
					Accept Friend Request
				<% end %>
			<% elsif user.status == 1 %>
				<%= link_to 'Remove', relationship_path(user.id), method: 'delete', remote: true, :class => 'pull-xs-right link-friend-list' %>
				<span class="pull-xs-right link-friend-list">|</span>
				<%= link_to 'Friend (New Message)', new_message_path, method: 'get', :class => 'pull-xs-right link-friend-list' %>

			<% elsif user.status == 2 %>
				<p class="pull-xs-right">Friend Request Sent</p>
			<% end %>
		</li>
	<% end %>
<% end %>

app/views/relationships/create.js.erb
$(".friends-list").html("<%= escape_javascript(render '/relationships/user_list') %>")

app/views/relationships/destroy.js.erb
$(".friends-list").html("<%= escape_javascript(render '/relationships/user_list') %>")

app/views/relationships/new.html.erb
<div class="row">
	<div class="col-md-10">
		<h5 class="text-primary">The more the merrier. Let get more friends!</h5>
		<div class="form-control friends-list">
		  <%= render '/relationships/user_list' %>
		</div>
	</div>
</div>

app/views/relationships/update.js.erb
$(".friends-list").html("<%= escape_javascript(render '/relationships/user_list') %>")