config/routes.rb
Rails.application.routes.draw do

  match 'auth/:provider/callback', to: 'sessions#create_with_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  resources :relationships
  resources :message_recipients
  resources :messages
	root 'sessions#login'
	resources :sessions, only: [:create]
	get 'login' => 'sessions#login'
	delete 'logout' => 'sessions#destroy'
  	resources :users
  	get 'messages_page' => 'users#show_message'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :name, presence: true
	validates :email, presence: true, uniqueness: {case_insensitive: false}
	has_many :messages
	has_many :message_recipients

	def self.from_omniauth(auth)
		@user = self.find_by(email: auth.uid)
		unless @user	
		    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
		      user.provider = auth.provider
		      user.uid = auth.uid
		      user.name = auth.info.name
		      user.email = auth.uid
		      user.password = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{auth.info.name}--")[0,6]
		      user.password_confirmation = user.password
		      user.oauth_token = auth.credentials.token
		      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		      user.save!
		      @user = user
		    end
		end
		return @user

	  end

	def list_senders
		self.message_recipients
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    set_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id

        redirect_to messages_page_path, flash: {success: 'User was successfully created.'}

      else
        redirect_to new_user_path, flash: {notice: @user.errors.full_messages.to_sentence}
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_message

    @senders = Message.joins("join users on messages.user_id = users.id").select("user_id, users.email as email, users.name as name, sum(case when messages.status = 1 then 1 else 0 end) as count").where(recipient_id: current_user.id).group("messages.user_id, users.email, users.name")
    @messages_list = Message.where(user_id: current_user.id).order('created_at DESC')
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, class: "form-control", placeholder: "Your Name"  %>
  </div>

  <div class="form-group">
    <%= f.label :email, "Email" %>
    <%= f.text_field :email, class: "form-control", placeholder: "Your Email"  %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'Password' %>
    <%= f.text_field :password, placeholder: "Your Password", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirm password' %>
    <%= f.text_field :password_confirmation, placeholder: "Re-enter the password", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit 'Sign up Your Account', class: "btn btn-secondary form-control" %>
  </div>

<% end %>

app/views/users/_show_message_content_form.html.erb
<!-- The scrollable area -->
<div class="jumbotro form-control data-spy="scroll" data-offset="50" style="height: 400px; overflow-y: scroll; position: relative;">

	<% if @messages_list %>		
		<% if @messages_list.count == 0 %>
			<p class="text-muted">There is no message to show</p>
		<% else %>

			<% @current_sender_id = 0 %>

			<% @messages_list.each do |mess| %>
				<% if @current_sender_id == 0 %>
					<h5 class="text-primary"><%= mess.user.name %></h5>	
					<% if mess.user_id == current_user.id  %>
						<cite> All of your sent messages here</cite>
						<br/>
					<% end %>
					<% @current_sender_id = 1 %>			
				<% end %>

				<div class="panel-group">
				  <div class="card">
				    <div class="card-header">
				      <h6 class="mb-0">
					    <a data-toggle="collapse" href="<%= '#' + 'clazz' + mess.id.to_s %>" onclick="
					    <% unless mess.user_id == current_user.id %>
					    	windChat_update_message(<%= mess.id %>);	
					    <% end %>
					    " >				    	
					      	<div class="row">
					      		<div class="col-md-7">
						        	<p class="text-muted"><%= mess.title %> 						        	
						        	</p>
									
					      		</div>
					      		<div class="col-md-5">
					      			<span class="text-muted small pull-xs-right">
										<% if mess.status == 2 && mess.user_id == current_user.id %>
											<%= mess.updated_at.strftime('%c') %>
										<% else %>
											<%= mess.created_at.strftime('%c') %>	
										<% end %>
					      				
					      				<% if mess.status == 1 %>
							        		<i class="fa fa-circle message-status pull-xs-right" id="<%= 'message-status-' +  mess.id.to_s %>" style="color: red"></i>
							        	<% else %>
							        		<i class="fa fa-circle-o message-status pull-xs-right" id="<%= 'message-status-' +  mess.id.to_s %>" style="color: #818a91"></i>
							        	<% end %>
					      			</span>
					      		</div>
					      	</div>				      	
				        </a>

				      </h6>			      
				    </div>
				    	
				    <% if mess.user_id != current_user.id && mess.status == 1 %>
				    	<div id="<%= 'clazz' + mess.id.to_s %>" class="panel-collapse collapse">
					      <div class="card-block">
						      <p class="small"><%= mess.content %></p>				      			      	
					      </div>
					    </div>
				    <% end %>
				    
				  </div>
				</div>
							
			<% end %>
		<% end %>		
	<% end %>
  
</div>	

app/views/users/_show_message_form.html.erb
<% if @senders.any? %>
	<% @senders.each_with_index do |sender, index| %>
		<% if index%2 == 0 %>
			<%= link_to message_path(sender.user_id), method: 'get', remote: true, :class => 'list-group-item list-group-item-action list-group-item-info' do %>		

				<span class="tag tag-default tag-pill pull-xs-right"><%= sender.count %></span><%= sender.name %>
			<% end %>
		<% else %>
			<%= link_to message_path(sender.user_id), method: 'get', remote: true, :class => 'list-group-item list-group-item-action list-group-item-warning' do %>		

				<span class="tag tag-default tag-pill pull-xs-right"><%= sender.count %></span><%= sender.name %>
			<% end %>				
		<% end %>
	<% end %>
<% else %>
	There is no message
<% end %>
	

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<ul class="list-inline">
  <li class="list-inline-item"><h4 class="text-primary">Create a new account or </h4></li>
  <li class="list-inline-item"><%= link_to "Log In with Facebook", "/auth/facebook", id: "sign_in", class:"btn btn-primary form-control" %></li>
</ul>

<div class="row">
	<div class="col-md-5">
		<%= render 'form', user: @user %>	
		<%= link_to 'Back', users_path %>
	</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/show_message.html.erb
<div class="row">
	<div class="col-md-4">
		<div class="form-control">
			<%= link_to 'Your Sent Message', message_path(current_user.id), method: 'get', remote: true, :class => 'list-group-item list-group-item-action' %>	
		</div>
		
		<div class="messages-list form-control">
			<%= render '/users/show_message_form' %>			
		</div>		
	</div>
	
	<div class="col-md-6 messages-content">
		<%= render '/users/show_message_content_form' %>
	</div>
	<div class="col-md-2">
		<%= link_to '+ New Message', new_message_path, :class => 'btn btn-secondary' %>
		<hr/>
		<%= link_to '+ Friends', new_relationship_path, :class => 'btn btn-secondary' %>		
	</div>
</div>

app/views/users/show_message.js.erb
$(".messages-content").html("<%= escape_javascript(render '/users/show_message_content_form') %>")